################################################################################
#
# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
# ies of the 
# Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
# PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
# CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################

from functools import lru_cache

@lru_cache
def getRequiredParametersMin():
    return {'1LDSBuffer': True,
            'ActivationAlt': False,
            'ActivationFuncCall': True,
            'ActivationFused': False,
            'AssertAIGreaterThanEqual': False,
            'AssertAILessThanEqual': False,
            'AssertFree0ElementMultiple': True,
            'AssertFree1ElementMultiple': True,
            'AssertSummationElementMultiple': True,
            'AssignedDerivedParameters': False,
            'AssignedProblemIndependentDerivedParameters': False,
            'BufferLoad': False,
            'BufferStore': False,
            'CUCount': False,
            'ClusterLocalRead': True,
            'CodeObjectVersion': False,
            'ConvertAfterDS': True,
            'CustomKernelName': False,
            'DebugStreamK': False,
            'DepthU': False,
            'DirectToLds': False,
            'DirectToLdsA': False,
            'DirectToLdsB': False,
            'DirectToVgprA': True,
            'DirectToVgprB': True,
            'DirectToVgprSparseMetadata': False,
            'EdgeType': False,
            'EnableF32XdlMathOp': False,
            'EnableMatrixInstruction': False,
            'ExpandPointerSwap': True,
            'ForceDisableShadowInit': True,
            'GlobalReadPerMfma': True,
            'GlobalReadVectorWidthA': True,
            'GlobalReadVectorWidthB': True,
            'GlobalSplitU': True,
            'GlobalSplitUAlgorithm': True,
            'GlobalSplitUCoalesced': True,
            'GlobalSplitUWorkGroupMappingRoundRobin': True,
            'GlobalWriteVectorWidth': False,
            'GroupLoadStore': True,
            'GuaranteeNoPartialA': False,
            'GuaranteeNoPartialB': False,
            'GuaranteeNoPartialMetadata': False,
            'ISA': True,
            'InnerUnroll': True,
            'InterleaveAlpha': False,
            'InternalSupportParams': False,
            'Kernel': True,
            'KernelLanguage': False,
            'KernelNameMin': False,
            'LSCA': False,
            'LSCB': False,
            'LSPA': False,
            'LSPB': False,
            'LVCA': False,
            'LVCB': False,
            'LVPA': False,
            'LVPB': False,
            'LdsBlockSizePerPadA': True,
            'LdsBlockSizePerPadB': True,
            'LdsBlockSizePerPadMetadata': True,
            'LdsBytesNoAmax': False,
            'LdsInitCVgprs': False,
            'LdsNumBytes': False,
            'LdsNumElementsAlignedA': False,
            'LdsNumElementsAlignedB': False,
            'LdsNumElementsAlignedMetadata': False,
            'LdsOffsetA': False,
            'LdsOffsetA_Blk': False,
            'LdsOffsetB': False,
            'LdsOffsetB_Blk': False,
            'LdsOffsetBias': False,
            'LdsOffsetBiasGSU': False,
            'LdsOffsetBiasNonGSU': False,
            'LdsOffsetMetadata': False,
            'LdsOffsetMetadata_Blk': False,
            'LdsPadA': True,
            'LdsPadB': True,
            'LdsPadMetadata': True,
            'LocalReadVectorWidth': True,
            'LocalSplitU': False,
            'LocalSplitUReuseLDS': False,
            'LocalWritePerMfma': True,
            'LocalWriteUseSgprA': False,
            'LocalWriteUseSgprB': False,
            'LoopIters': False,
            'LoopUnroll': False,
            'MFMA_BF16_1K': False,
            'MIArchVgpr': True,
            'MIBlock': False,
            'MIInputPerThread': False,
            'MIInputPerThreadA': False,
            'MIInputPerThreadB': False,
            'MIInputPerThreadMetadata': False,
            'MIOutputVectorWidth': False,
            'MIRegPerOut': False,
            'MIWaveGroup': False,
            'MIWaveTile': True,
            'MIWaveTileA': False,
            'MIWaveTileB': False,
            'MIWaveTileMetadata': False,
            'MacroTile0': False,
            'MacroTile1': False,
            'MacroTileA': False,
            'MacroTileB': False,
            'MagicDivAlg': False,
            'MatrixInstB': False,
            'MatrixInstBM': False,
            'MatrixInstBN': False,
            'MatrixInstK': False,
            'MatrixInstM': False,
            'MatrixInstN': False,
            'MatrixInstruction': False,
            'MaxOccupancy': True,
            'NoLdsWriteCode': False,
            'NoReject': False,
            'NoTailLoop': False,
            'NonTemporal': True,
            'NonTemporalA': True,
            'NonTemporalB': True,
            'NonTemporalC': True,
            'NonTemporalD': True,
            'NonTemporalE': False,
            'NonTemporalMetadata': True,
            'NonTemporalWS': False,
            'NumElementsPerBatchStore': True,
            'NumElementsPerThread': False,
            'NumGlobalWriteVectorsPerThread': False,
            'NumLoadsA': False,
            'NumLoadsB': False,
            'NumLoadsCoalescedA': True,
            'NumLoadsCoalescedB': True,
            'NumLoadsPerpendicularA': False,
            'NumLoadsPerpendicularB': False,
            'NumThreads': False,
            'OptNoLoadLoop': True,
            'PackedC0IdxChars': False,
            'PackedC0IndicesX': False,
            'PackedC1IdxChars': False,
            'PackedC1IndicesX': False,
            'PrefetchGlobalRead': True,
            'PrefetchLocalRead': True,
            'PreloadKernArgs': True,
            'ProblemType': False,
            'ScheduleGlobalRead': False,
            'ScheduleIterAlg': True,
            'ScheduleLocalWrite': False,
            'SolutionIndex': False,
            'SolutionNameMin': False,
            'SourceSwap': True,
            'StaggerU': True,
            'StaggerUMapping': True,
            'StaggerUStride': True,
            'StorePriorityOpt': True,
            'StoreRemapVectorWidth': True,
            'StoreSyncOpt': True,
            'StoreVectorWidth': True,
            'StreamK': True,
            'StreamKAtomic': False,
            'StreamKXCCMapping': True,
            'SubGroup0': False,
            'SubGroup1': False,
            'SubGroupA': False,
            'SubGroupB': False,
            'SuppressNoLoadLoop': False,
            'ThreadTile': False,
            'ThreadTile0': False,
            'ThreadTile1': False,
            'ThreadTileA': False,
            'ThreadTileB': False,
            'TransposeLDS': True,
            'TransposeLDSMetadata': False,
            'ULSGRODoubleG2L': False,
            'UnrollLoopSwapGlobalReadOrder': True,
            'UnrollMajorLDSA': False,
            'UnrollMajorLDSB': False,
            'UnrollMajorLDSMetadata': False,
            'Use64bShadowLimit': True,
            'UseInstOffsetForGRO': True,
            'UseSgprForGRO': True,
            'Valid': False,
            'VectorStore': True,
            'VectorWidthA': True,
            'VectorWidthB': True,
            'WaveSeparateGlobalReadA': True,
            'WaveSeparateGlobalReadB': True,
            'WaveSeparateGlobalReadMetadata': False,
            'WavefrontSize': True,
            'WorkGroup': True,
            'WorkGroupMapping': True,
            'WorkGroupMappingXCC': True,
            'WorkGroupMappingXCCGroup': True,
            'WorkGroupReduction': False,
            'WorkspaceCheck': False,
            '_DepthU': False,
            '_DepthUA': False,
            '_DepthUB': False,
            '_DepthUMetadata': False,
            '_GlobalAccumulation': False,
            '_UseSgprForGRO': False,
            '_VectorStore': False,
            '_WorkspaceSizePerElemBias': False,
            '_WorkspaceSizePerElemC': False,
            '_staggerStrideShift': False,
            'codeObjectFile': False,
            'reorderGRInstForDTVA': False,
            'reorderGRInstForDTVB': False,
            'tailLoopOptA': False,
            'tailLoopOptB': False}
