algorithm: GA
pop_size: 512
n_gen: 20
tol: 0.0001
period: 0 # 0 disables it
max_iters: 100
seed: 0
verbose: 1
log_file: optimization.log
survival:
  name: fitness
#  ratio: 1.0 # TODO
selection:
  name: tournament
  tournament:
    k: 2
  truncation:
    elite_ratio: 0.231579
  beta:
    a: 1
    b: 2.5
  ranked_round_robin: # Need to test this
    var_name: MatrixInstruction #MatrixInstruction # null means cluster fitness
    mode: elite # 'elite' is the default and will pop the best of each group, rank will sample with ranked prob
  common:
    ratio: 0.5
    elitism: 0.05 #0.14285714285 # 1 / 7
    replacement: true
crossover:
  name: ux
  common:
    mode: random
    prob: 0.9 # Should be in the (0.8, 1.0) range usually
mutation:
  prob: null #0.05869674 # If set should be something small (e.g. 0.02~0.06), set to 1 / n_params by default
#  weights:
#    MatrixInstruction: 2.1
#    DepthU: 2.1
# weights' role is to increase the mutation rate for certain parameters, the final prob will be prob * w
# after proper testing, if this is necessary we can make it self-adaptive/dynamic (diversity based)


