_requiredParametersFull = {
    "InnerUnroll": True,
    "KernelLanguage": True,
    "LdsPadA": True,
    "LdsPadB": True,
    "LdsPadMetadata": True,
    "LdsBlockSizePerPadA": True,
    "LdsBlockSizePerPadB": True,
    "LdsBlockSizePerPadMetadata": True,
    "TransposeLDS": True,
    "MaxOccupancy": True,
    "VectorWidthA": True,
    "VectorWidthB": True,
    "VectorStore": True,
    "StoreVectorWidth": True,
    "GlobalReadVectorWidthA": True,
    "GlobalReadVectorWidthB": True,
    "LocalReadVectorWidth": True,
    "WaveSeparateGlobalReadA": True,
    "WaveSeparateGlobalReadB": True,
    "UnrollLoopSwapGlobalReadOrder": True,
    "PrefetchGlobalRead": True,
    "PrefetchLocalRead": True,
    "ClusterLocalRead": True,
    "SuppressNoLoadLoop": True,
    "ExpandPointerSwap": True,
    "ScheduleGlobalRead": True,
    "ScheduleLocalWrite": True,
    "ScheduleIterAlg": True,
    "GlobalReadPerMfma": True,
    "LocalWritePerMfma": True,
    "InterleaveAlpha": True,
    "OptNoLoadLoop": True,
    "BufferLoad": True,
    "BufferStore": True,
    "DirectToVgprA": True,
    "DirectToVgprB": True,
    "DirectToVgprSparseMetadata": True,
    "DirectToLds": True,
    "UseSgprForGRO": True,
    "UseInstOffsetForGRO": True,
    "AssertSummationElementMultiple": True,
    "AssertFree0ElementMultiple": True,
    "AssertFree1ElementMultiple": True,
    "AssertAIGreaterThanEqual": True,
    "AssertAILessThanEqual": True,
    "StaggerU": True,
    "StaggerUStride": True,
    "StaggerUMapping": True,
    "MagicDivAlg": True,
    "GlobalSplitU": True,
    "GlobalSplitUAlgorithm": True,
    "GlobalSplitUCoalesced": True,
    "GlobalSplitUWorkGroupMappingRoundRobin": True,
    "Use64bShadowLimit": True,
    "NumLoadsCoalescedA": True,
    "NumLoadsCoalescedB": True,
    "WorkGroup": True,
    "WorkGroupMapping": True,
    "WorkGroupMappingXCC": True,
    "WorkGroupMappingXCCGroup": True,
    "ThreadTile": True,
    "WavefrontSize": True,
    "MatrixInstruction": True,
    "1LDSBuffer": True,
    "DepthU": True,
    "NonTemporalE": True,
    "NonTemporalD": True,
    "NonTemporalC": True,
    "NonTemporalA": True,
    "NonTemporalB": True,
    "NonTemporalWS": True,
    "NonTemporalMetadata": True,
    "NonTemporal": True,
    "PreloadKernArgs": True,
    "CustomKernelName": True,
    "NoReject": True,
    "MinVgprNumber": True,
    "MaxVgprNumber": True,
    "TotalVgprNumber": True,
    "StoreRemapVectorWidth": True,
    "SourceSwap": True,
    "StorePriorityOpt": True,
    "NumElementsPerBatchStore": True,
    "StoreSyncOpt": True,
    "GroupLoadStore": True,
    "MIArchVgpr": True,
    "StreamK": True,
    "StreamKAtomic": True,
    "StreamKXCCMapping": True,
    "DebugStreamK": True,
    "ActivationFused": True,
    "ActivationFuncCall": True,
    "ActivationAlt": True,
    "WorkGroupReduction": True,
    "ConvertAfterDS": True,
    "ForceDisableShadowInit": True,
    "ISA": True,
    "MIWaveTile": True,
}


_requiredParametersMin = {'ProblemType': False, 'InternalSupportParams': False, 'InnerUnroll': True, 'KernelLanguage': False, 'LdsPadA': True, 'LdsPadB': True, 'LdsPadMetadata': True, 'LdsBlockSizePerPadA': True, 'LdsBlockSizePerPadB': True, 'LdsBlockSizePerPadMetadata': True, 'TransposeLDS': True, 'MaxOccupancy': True, 'VectorWidthA': True, 'VectorWidthB': True, 'VectorStore': True, 'StoreVectorWidth': True, 'GlobalReadVectorWidthA': True, 'GlobalReadVectorWidthB': True, 'LocalReadVectorWidth': True, 'WaveSeparateGlobalReadA': True, 'WaveSeparateGlobalReadB': True, 'WaveSeparateGlobalReadMetadata': False, 'UnrollLoopSwapGlobalReadOrder': True, 'PrefetchGlobalRead': True, 'PrefetchLocalRead': True, 'ClusterLocalRead': True, 'SuppressNoLoadLoop': False, 'ExpandPointerSwap': True, 'ScheduleGlobalRead': False, 'ScheduleLocalWrite': False, 'ScheduleIterAlg': True, 'GlobalReadPerMfma': True, 'LocalWritePerMfma': True, 'InterleaveAlpha': False, 'OptNoLoadLoop': True, 'BufferLoad': False, 'BufferStore': False, 'DirectToVgprA': True, 'DirectToVgprB': False, 'DirectToVgprSparseMetadata': False, 'DirectToLds': False, 'UseSgprForGRO': True, 'UseInstOffsetForGRO': True, 'AssertSummationElementMultiple': True, 'AssertFree0ElementMultiple': True, 'AssertFree1ElementMultiple': True, 'AssertAIGreaterThanEqual': False, 'AssertAILessThanEqual': False, 'StaggerU': True, 'StaggerUStride': True, 'StaggerUMapping': True, 'MagicDivAlg': False, 'GlobalSplitU': True, 'GlobalSplitUAlgorithm': True, 'GlobalSplitUCoalesced': True, 'GlobalSplitUWorkGroupMappingRoundRobin': True, 'Use64bShadowLimit': True, 'NumLoadsCoalescedA': True, 'NumLoadsCoalescedB': True, 'WorkGroup': True, 'WorkGroupMapping': True, 'WorkGroupMappingXCC': True, 'WorkGroupMappingXCCGroup': True, 'ThreadTile': False, 'WavefrontSize': True, 'MatrixInstruction': False, '1LDSBuffer': True, 'DepthU': False, 'NonTemporalE': False, 'NonTemporalD': True, 'NonTemporalC': True, 'NonTemporalA': True, 'NonTemporalB': True, 'NonTemporalWS': False, 'NonTemporalMetadata': True, 'NonTemporal': True, 'PreloadKernArgs': True, 'CustomKernelName': False, 'NoReject': False, 'MinVgprNumber': False, 'MaxVgprNumber': False, 'TotalVgprNumber': False, 'StoreRemapVectorWidth': True, 'SourceSwap': True, 'StorePriorityOpt': True, 'NumElementsPerBatchStore': True, 'StoreSyncOpt': True, 'GroupLoadStore': False, 'MIArchVgpr': True, 'StreamK': False, 'StreamKAtomic': False, 'StreamKXCCMapping': False, 'DebugStreamK': False, 'ActivationFused': False, 'ActivationFuncCall': True, 'ActivationAlt': False, 'WorkGroupReduction': False, 'ConvertAfterDS': True, 'ForceDisableShadowInit': False, 'ISA': True, 'CodeObjectVersion': False, 'AssignedDerivedParameters': False, 'AssignedProblemIndependentDerivedParameters': False, 'CUCount': False, 'DepthULdsDivisor': False, 'DirectToLdsA': False, 'DirectToLdsB': False, 'EdgeType': False, 'EnableF32XdlMathOp': False, 'EnableMatrixInstruction': False, 'GlobalWriteVectorWidth': False, 'GuaranteeNoPartialA': False, 'GuaranteeNoPartialB': False, 'GuaranteeNoPartialMetadata': False, 'LSCA': False, 'LSCB': False, 'LSPA': False, 'LSPB': False, 'LVCA': False, 'LVCB': False, 'LVPA': False, 'LVPB': False, 'LdsBlockSizePerPad': False, 'LdsInitCVgprs': False, 'LdsNumBytes': False, 'LdsNumElements': False, 'LdsNumElementsAlignedA': False, 'LdsNumElementsAlignedB': False, 'LdsNumElementsAlignedMetadata': False, 'LdsOffsetA': False, 'LdsOffsetA_Blk': False, 'LdsOffsetB': False, 'LdsOffsetB_Blk': False, 'LdsOffsetBias': False, 'LdsOffsetBiasGSU': False, 'LdsOffsetBiasNonGSU': False, 'LdsOffsetMetadata': False, 'LdsOffsetMetadata_Blk': False, 'LocalSplitU': False, 'LocalWriteUseSgprA': False, 'LocalWriteUseSgprB': False, 'LoopIters': False, 'LoopUnroll': False, 'MFMA_BF16_1K': False, 'MIBlock': False, 'MIInputPerThread': False, 'MIInputPerThreadA': False, 'MIInputPerThreadB': False, 'MIOutputVectorWidth': False, 'MIRegPerOut': False, 'MIWaveGroup': False, 'MIWaveTile': True, 'MIWaveTileA': False, 'MIWaveTileB': False, 'MIWaveTileMetadata': False, 'MacroTile0': False, 'MacroTile1': False, 'MacroTileA': False, 'MacroTileB': False, 'MatrixInstB': False, 'MatrixInstBM': False, 'MatrixInstBN': False, 'MatrixInstK': False, 'MatrixInstM': False, 'MatrixInstN': False, 'NoLdsWriteCode': False, 'NoTailLoop': False, 'NumElementsPerThread': False, 'NumGlobalWriteVectorsPerThread': False, 'NumLoadsA': False, 'NumLoadsB': False, 'NumLoadsPerpendicularA': False, 'NumLoadsPerpendicularB': False, 'NumThreads': False, 'PackedC0IdxChars': False, 'PackedC0IndicesX': False, 'PackedC1IdxChars': False, 'PackedC1IndicesX': False, 'SolutionIndex': False, 'SolutionNameMin': False, 'SubGroup0': False, 'SubGroup1': False, 'SubGroupA': False, 'SubGroupB': False, 'ThreadTile0': False, 'ThreadTile1': False, 'ThreadTileA': False, 'ThreadTileB': False, 'TransposeLDSMetadata': False, 'UnrollMajorLDSA': False, 'UnrollMajorLDSB': False, 'UnrollMajorLDSMetadata': False, 'Valid': False, 'VectorWidth': False, 'WorkspaceCheck': False, '_DepthU': False, '_DepthUA': False, '_DepthUB': False, '_DepthULds': False, '_DepthUMetadata': False, '_GlobalAccumulation': False, '_UseSgprForGRO': False, '_VectorStore': False, '_WorkspaceSizePerElemBias': False, '_WorkspaceSizePerElemC': False, '_staggerStrideShift': False, 'allowLRVWforTLUandMI': False, 'LdsBytesNoAmax': False, 'ULSGRODoubleG2L': False, 'codeObjectFile': False, 'Kernel': True}


def getRequiredParametersFull():
    return _requiredParametersFull

def getRequiredParametersMin():
    return _requiredParametersMin


# Begin comparison tests
if __name__ == "__main__":
    from deepdiff import DeepDiff
    reqParamA = {'ProblemType': False, 'InternalSupportParams': False, 'InnerUnroll': True, 'KernelLanguage': False, 'LdsPadA': True, 'LdsPadB': True, 'LdsPadMetadata': True, 'LdsBlockSizePerPadA': True, 'LdsBlockSizePerPadB': True, 'LdsBlockSizePerPadMetadata': True, 'TransposeLDS': True, 'MaxOccupancy': True, 'VectorWidthA': True, 'VectorWidthB': True, 'VectorStore': True, 'StoreVectorWidth': True, 'GlobalReadVectorWidthA': True, 'GlobalReadVectorWidthB': True, 'LocalReadVectorWidth': True, 'WaveSeparateGlobalReadA': True, 'WaveSeparateGlobalReadB': True, 'WaveSeparateGlobalReadMetadata': False, 'UnrollLoopSwapGlobalReadOrder': True, 'PrefetchGlobalRead': True, 'PrefetchLocalRead': True, 'ClusterLocalRead': True, 'SuppressNoLoadLoop': False, 'ExpandPointerSwap': True, 'ScheduleGlobalRead': False, 'ScheduleLocalWrite': False, 'ScheduleIterAlg': True, 'GlobalReadPerMfma': True, 'LocalWritePerMfma': True, 'InterleaveAlpha': False, 'OptNoLoadLoop': True, 'BufferLoad': False, 'BufferStore': False, 'DirectToVgprA': True, 'DirectToVgprB': False, 'DirectToVgprSparseMetadata': False, 'DirectToLds': False, 'UseSgprForGRO': True, 'UseInstOffsetForGRO': True, 'AssertSummationElementMultiple': True, 'AssertFree0ElementMultiple': True, 'AssertFree1ElementMultiple': True, 'AssertAIGreaterThanEqual': False, 'AssertAILessThanEqual': False, 'StaggerU': True, 'StaggerUStride': True, 'StaggerUMapping': True, 'MagicDivAlg': False, 'GlobalSplitU': True, 'GlobalSplitUAlgorithm': True, 'GlobalSplitUCoalesced': True, 'GlobalSplitUWorkGroupMappingRoundRobin': True, 'Use64bShadowLimit': True, 'NumLoadsCoalescedA': True, 'NumLoadsCoalescedB': True, 'WorkGroup': True, 'WorkGroupMapping': True, 'WorkGroupMappingXCC': True, 'WorkGroupMappingXCCGroup': True, 'ThreadTile': False, 'WavefrontSize': True, 'MatrixInstruction': False, '1LDSBuffer': True, 'DepthU': False, 'NonTemporalE': False, 'NonTemporalD': True, 'NonTemporalC': True, 'NonTemporalA': True, 'NonTemporalB': True, 'NonTemporalWS': False, 'NonTemporalMetadata': True, 'NonTemporal': True, 'PreloadKernArgs': True, 'CustomKernelName': False, 'NoReject': False, 'MinVgprNumber': False, 'MaxVgprNumber': False, 'TotalVgprNumber': False, 'StoreRemapVectorWidth': True, 'SourceSwap': True, 'StorePriorityOpt': True, 'NumElementsPerBatchStore': True, 'StoreSyncOpt': True, 'GroupLoadStore': False, 'MIArchVgpr': True, 'StreamK': False, 'StreamKAtomic': False, 'StreamKXCCMapping': False, 'DebugStreamK': False, 'ActivationFused': False, 'ActivationFuncCall': True, 'ActivationAlt': False, 'WorkGroupReduction': False, 'ConvertAfterDS': True, 'ForceDisableShadowInit': False, 'ISA': True, 'CodeObjectVersion': False, 'AssignedDerivedParameters': False, 'AssignedProblemIndependentDerivedParameters': False, 'CUCount': False, 'DepthULdsDivisor': False, 'DirectToLdsA': False, 'DirectToLdsB': False, 'EdgeType': False, 'EnableF32XdlMathOp': False, 'EnableMatrixInstruction': False, 'GlobalWriteVectorWidth': False, 'GuaranteeNoPartialA': False, 'GuaranteeNoPartialB': False, 'GuaranteeNoPartialMetadata': False, 'LSCA': False, 'LSCB': False, 'LSPA': False, 'LSPB': False, 'LVCA': False, 'LVCB': False, 'LVPA': False, 'LVPB': False, 'LdsBlockSizePerPad': False, 'LdsInitCVgprs': False, 'LdsNumBytes': False, 'LdsNumElements': False, 'LdsNumElementsAlignedA': False, 'LdsNumElementsAlignedB': False, 'LdsNumElementsAlignedMetadata': False, 'LdsOffsetA': False, 'LdsOffsetA_Blk': False, 'LdsOffsetB': False, 'LdsOffsetB_Blk': False, 'LdsOffsetBias': False, 'LdsOffsetBiasGSU': False, 'LdsOffsetBiasNonGSU': False, 'LdsOffsetMetadata': False, 'LdsOffsetMetadata_Blk': False, 'LocalSplitU': False, 'LocalWriteUseSgprA': False, 'LocalWriteUseSgprB': False, 'LoopIters': False, 'LoopUnroll': False, 'MFMA_BF16_1K': False, 'MIBlock': False, 'MIInputPerThread': False, 'MIInputPerThreadA': False, 'MIInputPerThreadB': False, 'MIOutputVectorWidth': False, 'MIRegPerOut': False, 'MIWaveGroup': False, 'MIWaveTile': True, 'MIWaveTileA': False, 'MIWaveTileB': False, 'MIWaveTileMetadata': False, 'MacroTile0': False, 'MacroTile1': False, 'MacroTileA': False, 'MacroTileB': False, 'MatrixInstB': False, 'MatrixInstBM': False, 'MatrixInstBN': False, 'MatrixInstK': False, 'MatrixInstM': False, 'MatrixInstN': False, 'NoLdsWriteCode': False, 'NoTailLoop': False, 'NumElementsPerThread': False, 'NumGlobalWriteVectorsPerThread': False, 'NumLoadsA': False, 'NumLoadsB': False, 'NumLoadsPerpendicularA': False, 'NumLoadsPerpendicularB': False, 'NumThreads': False, 'PackedC0IdxChars': False, 'PackedC0IndicesX': False, 'PackedC1IdxChars': False, 'PackedC1IndicesX': False, 'SolutionIndex': False, 'SolutionNameMin': False, 'SubGroup0': False, 'SubGroup1': False, 'SubGroupA': False, 'SubGroupB': False, 'ThreadTile0': False, 'ThreadTile1': False, 'ThreadTileA': False, 'ThreadTileB': False, 'TransposeLDSMetadata': False, 'UnrollMajorLDSA': False, 'UnrollMajorLDSB': False, 'UnrollMajorLDSMetadata': False, 'Valid': False, 'VectorWidth': False, 'WorkspaceCheck': False, '_DepthU': False, '_DepthUA': False, '_DepthUB': False, '_DepthULds': False, '_DepthUMetadata': False, '_GlobalAccumulation': False, '_UseSgprForGRO': False, '_VectorStore': False, '_WorkspaceSizePerElemBias': False, '_WorkspaceSizePerElemC': False, '_staggerStrideShift': False, 'allowLRVWforTLUandMI': False, 'LdsBytesNoAmax': False, 'ULSGRODoubleG2L': False, 'codeObjectFile': False, 'Kernel': True}

    print(DeepDiff(reqParamA, _requiredParametersMin, ignore_order=True).pretty())